services:
  - type: web
    name: scuric-dashboard
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      # Wichtig: Leite /api/dialer/* und alle API-Anfragen an den Backend-Service weiter
      # Explizite Routen für spezifische PowerDialer-Endpunkte
      - type: rewrite
        source: /api/dialer/*
        destination: https://dashboard-l-backend.onrender.com/api/dialer/:splat
      # Vermeide doppelte /api Präfixe
      - type: rewrite
        source: /api/api/dialer/*
        destination: https://dashboard-l-backend.onrender.com/api/dialer/:splat
      # Auth und allgemeine API-Routen
      - type: rewrite
        source: /api/auth/*
        destination: https://dashboard-l-backend.onrender.com/api/auth/:splat
      - type: rewrite
        source: /api/*
        destination: https://dashboard-l-backend.onrender.com/api/:splat
      # Client-Routen
      - type: rewrite
        source: /portal/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html