services:
  - type: web
    name: scuric-dashboard
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /portal/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html